# Generated by Django 6.0.2 on 2026-04-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=10)),
                ('reviews', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('avatar_initials', models.CharField(max_length=2)),
            ],
        ),
    ]
